#!/bin/bash 
#####################################################################
#Project		:	RetroPie_BGM_Player
#Git			:	https://github.com/Naprosnia/RetroPie_BGM_Player
#####################################################################
#Script Name	:	mp3player.sh
#Date			:	20190224	(YYYYMMDD)
#Description	:	Start mpg123.
#Usage			:	It should be called from bgm_launcher.sh.
#Author       	:	Luis Torres aka Naprosnia
#####################################################################
#Credits		:	crcerror : https://github.com/crcerror
#####################################################################

[[ "$(pgrep -c -f $(basename $0))" -gt 1 ]] && exit

RP="$HOME/RetroPie"
BGMMUSICS="$RP/roms/music"
BGM="$HOME/RetroPie-BGM-Player"
BGMSETTINGS="$BGM/bgm_settings.ini"
BGMLAUNCHER="$BGM/bgm_launcher"
BGMMP3PLAYER="$BGMLAUNCHER/mp3player"

source $BGMSETTINGS >/dev/null 2>&1

bgm_mp3volume=$(( 32768*$bgm_volume/100 ))

checkmp3="ls -1 $BGMMUSICS/*.mp3 2>/dev/null | wc -l"

if [ $checkmp3 -gt 0 ]; then
	mpg123 -q -f $bgm_mp3volume -Z $BGMMUSICS/*.mp3 >/dev/null 2>&1
else
	sleep 10
fi