#!/bin/bash 
#####################################################################
#Project		:	RetroPie_BGM_Player
#Git			:	https://github.com/Naprosnia/RetroPie_BGM_Player
#####################################################################
#Script Name	:	both.sh
#Date			:	20190224	(YYYYMMDD)
#Description	:	Start sequence of both players.
#Usage			:	It should be called from bgm_launcher.sh.
#Author       	:	Luis Torres aka Naprosnia
#####################################################################
#Credits		:	crcerror : https://github.com/crcerror
#####################################################################

[[ "$(pgrep -c -f $(basename $0))" -gt 1 ]] && exit

BGM="$HOME/RetroPie-BGM-Player"
BGMLAUNCHER="$BGM/bgm_launcher"
BGMBOTH="$BGMLAUNCHER/both"

if [ -f $BGMBOTH/sequence ] && [ $(wc -l < $BGMBOTH/sequence) -gt 1 ]; then
	./$BGMBOTH/sequence >/dev/null 2>&1
else
	sleep 10
fi