#!/bin/bash
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/5.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/pacman.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/6.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/03.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/2.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/01.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/3.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/1.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/02.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/4.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/5.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/pacman.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/6.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/03.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/2.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/01.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/3.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/1.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/02.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/4.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/5.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/pacman.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/6.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/03.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/2.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/01.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/3.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/1.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/02.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/4.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/5.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/pacman.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/6.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/03.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/2.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/01.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/3.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/1.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/02.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/4.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/5.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/pacman.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/6.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/03.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/2.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/01.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/3.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/1.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/02.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/4.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/5.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/pacman.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/6.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/03.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/2.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/01.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/3.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/1.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/02.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/4.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/5.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/pacman.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/6.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/03.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/2.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/01.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/3.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/1.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/02.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/4.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/5.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/pacman.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/6.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/03.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/2.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/01.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/3.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/1.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/02.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/4.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/5.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/pacman.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/6.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/03.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/2.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/01.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/3.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/1.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/02.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/4.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/5.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/pacman.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/6.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/03.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/2.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/01.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/3.mp3 >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/1.mp3 >/dev/null 2>&1
bash /home/pi/RetroPie-BGM-Player/VGMPlay/vgmplay /home/pi/RetroPie/roms/music/02.vgz  >/dev/null 2>&1
mpg123 -q -f 16384 -Z /home/pi/RetroPie/roms/music/4.mp3 >/dev/null 2>&1
